-- MySQL Script generated by MySQL Workbench
-- Seg 01 Jan 2018 14:11:51 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SGVC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SGVC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SGVC` DEFAULT CHARACTER SET utf8 ;
USE `SGVC` ;

-- -----------------------------------------------------
-- Table `SGVC`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGVC`.`staff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGVC`.`itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGVC`.`itens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` VARCHAR(45) NOT NULL,
  `quantidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGVC`.`transacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGVC`.`transacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `itens_id` INT NOT NULL,
  `staff_id` INT NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`id`, `itens_id`, `staff_id`),
  INDEX `fk_transacoes_itens_idx` (`itens_id` ASC),
  INDEX `fk_transacoes_staff1_idx` (`staff_id` ASC),
  CONSTRAINT `fk_transacoes_itens`
    FOREIGN KEY (`itens_id`)
    REFERENCES `SGVC`.`itens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transacoes_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `SGVC`.`staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
